name: GitHub Metrics
on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # ğŸ§  Base
          base: header, activity, community, repositories
          base_indepth: yes

          # ğŸ•“ Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # ğŸŒ Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage

          # ğŸ“ˆ Repositories
          plugin_repositories: yes
          plugin_repositories_featured: cssidhu0001

          # ğŸ Snake Contribution Graph
          plugin_sponsors: no

          # Theme & Config
          config_timezone: Asia/Kolkata
          config_order: base, activity, languages, repositories
